from __future__ import annotations

from fastapi import FastAPI

from errors import empty_question_error, forced_error
from schemas import ExternalAgentHealth, ExternalAgentRequest, ExternalAgentResponse


AGENT_ID = "example_external_agent"
AGENT_NAME = "Example External Agent"
VERSION = "0.1.0"

app = FastAPI(title=AGENT_NAME, version=VERSION)


@app.get("/health", response_model=ExternalAgentHealth)
async def health() -> ExternalAgentHealth:
    return ExternalAgentHealth(
        schema_version="external_agent_health_v0",
        status="ok",
        agent_id=AGENT_ID,
        agent_name=AGENT_NAME,
        version=VERSION,
        capabilities=["example", "structured_response", "fail_soft"],
        input_modes=["question"],
        output_modes=["external_agent_response_v0"],
        llm_configured=False,
        tools_configured=True,
        data_ready=True,
        max_concurrency=1,
        timeout_seconds=15,
        warnings=["scaffold only; not connected to AGENT_TOOLS"],
    )


@app.post("/v1/agent/invoke", response_model=ExternalAgentResponse)
async def invoke(req: ExternalAgentRequest) -> ExternalAgentResponse:
    question = req.question.strip()
    if not question:
        return _error_response(req, empty_question_error(), "Question is empty.")

    if bool(req.options.get("force_error")) or "force_error" in question.lower():
        return _error_response(req, forced_error(), "Forced scaffold error.")

    if bool(req.options.get("needs_clarification")) or _looks_ambiguous(question):
        return ExternalAgentResponse(
            schema_version="external_agent_response_v0",
            request_id=req.request_id,
            agent_id=AGENT_ID,
            status="needs_clarification",
            question=req.question,
            parsed_request={"intent": "needs_clarification"},
            tool_result={},
            native_answer="The request is ambiguous and needs one more concrete target.",
            answer="Please provide a specific target, time range, or entity before analysis.",
            answer_mode=str(req.options.get("answer_mode", "structured")),
            confidence=0.2,
            key_points=["The scaffold detected an ambiguous request."],
            evidence=[],
            data_sources=[],
            warnings=["needs_clarification example path"],
            errors=[],
        )

    tool_result = {
        "example_metric": 1.0,
        "calculation": "deterministic scaffold output",
        "input_length": len(question),
    }
    return ExternalAgentResponse(
        schema_version="external_agent_response_v0",
        request_id=req.request_id,
        agent_id=AGENT_ID,
        status="ok",
        question=req.question,
        parsed_request={
            "intent": "example_analysis",
            "subtask": req.subtask,
            "language": req.language,
        },
        tool_result=tool_result,
        native_answer="This is a deterministic scaffold response.",
        answer=(
            "This scaffold received the request and returned a structured, "
            "deterministic example response. It is not investment advice."
        ),
        answer_mode=str(req.options.get("answer_mode", "structured")),
        confidence=0.75,
        key_points=[
            "The service is reachable.",
            "The response follows external_agent_response_v0.",
            "No real LLM or network dependency was used.",
        ],
        evidence=[
            {
                "source": "scaffold",
                "summary": "Deterministic response generated by local example code.",
            }
        ],
        data_sources=[
            {
                "name": "none",
                "version": VERSION,
                "description": "No external data source is used by this scaffold.",
            }
        ],
        warnings=[],
        errors=[],
    )


def _error_response(req: ExternalAgentRequest, err, answer: str) -> ExternalAgentResponse:
    return ExternalAgentResponse(
        schema_version="external_agent_response_v0",
        request_id=req.request_id,
        agent_id=AGENT_ID,
        status="error",
        question=req.question,
        parsed_request={},
        tool_result={},
        native_answer=answer,
        answer=answer,
        answer_mode=str(req.options.get("answer_mode", "structured")),
        confidence=0.0,
        key_points=[],
        evidence=[],
        data_sources=[],
        warnings=[],
        errors=[err],
    )


def _looks_ambiguous(question: str) -> bool:
    lowered = question.lower()
    return "clarify" in lowered or "ambiguous" in lowered or "unclear" in lowered

